// This class was generated by the JAXRPC RI, do not edit.
// Contents subject to change without notice.

package com.msaf.validador.wsclient;


public class ConsultaClienteResponse {
    protected javax.xml.soap.SOAPElement[] _return;
    
    public ConsultaClienteResponse() {
    }
    
    public ConsultaClienteResponse(javax.xml.soap.SOAPElement[] _return) {
        this._return = _return;
    }
    
    public javax.xml.soap.SOAPElement[] get_return() {
        return _return;
    }
    
    public void set_return(javax.xml.soap.SOAPElement[] _return) {
        this._return = _return;
    }
}
