// This class was generated by the JAXRPC RI, do not edit.
// Contents subject to change without notice.

package com.msaf.validador.wsclient;


public class ConsultaCliente {
    protected java.lang.String arg0;
    protected int arg1;
    protected int arg2;
    protected java.lang.String arg3;
    
    public ConsultaCliente() {
    }
    
    public ConsultaCliente(java.lang.String arg0, int arg1, int arg2, java.lang.String arg3) {
        this.arg0 = arg0;
        this.arg1 = arg1;
        this.arg2 = arg2;
        this.arg3 = arg3;
    }
    
    public java.lang.String getArg0() {
        return arg0;
    }
    
    public void setArg0(java.lang.String arg0) {
        this.arg0 = arg0;
    }
    
    public int getArg1() {
        return arg1;
    }
    
    public void setArg1(int arg1) {
        this.arg1 = arg1;
    }
    
    public int getArg2() {
        return arg2;
    }
    
    public void setArg2(int arg2) {
        this.arg2 = arg2;
    }
    
    public java.lang.String getArg3() {
        return arg3;
    }
    
    public void setArg3(java.lang.String arg3) {
        this.arg3 = arg3;
    }
}
