// This class was generated by the JAXRPC RI, do not edit.
// Contents subject to change without notice.

package com.msaf.validador.wsclient;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.client.ServiceExceptionImpl;
import com.sun.xml.rpc.util.exception.*;
import com.sun.xml.rpc.client.HandlerChainImpl;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.rpc.handler.HandlerChain;
import javax.xml.rpc.handler.HandlerInfo;
import javax.xml.namespace.QName;

public class ValidadorDelegateImplService_Impl extends com.sun.xml.rpc.client.BasicService implements ValidadorDelegateImplService {
    private static final QName serviceName = new QName("http://webservices.validador.msaf.com/", "ValidadorDelegateImplService");
    private static final QName ns1_ValidadorDelegateImplPort_QNAME = new QName("http://webservices.validador.msaf.com/", "ValidadorDelegateImplPort");
    private static final Class validadorDelegateImpl_PortClass = com.msaf.validador.wsclient.ValidadorDelegateImpl.class;
    
    public ValidadorDelegateImplService_Impl() {
        super(serviceName, new QName[] {
                        ns1_ValidadorDelegateImplPort_QNAME
                    },
            new com.msaf.validador.wsclient.ValidadorDelegateImplService_SerializerRegistry().getRegistry());
        
    }
    
    public java.rmi.Remote getPort(QName portName, Class serviceDefInterface) throws ServiceException {
        try {
            if (portName.equals(ns1_ValidadorDelegateImplPort_QNAME) &&
                serviceDefInterface.equals(validadorDelegateImpl_PortClass)) {
                return getValidadorDelegateImplPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(portName, serviceDefInterface);
    }
    
    public java.rmi.Remote getPort(Class serviceDefInterface) throws ServiceException {
        try {
            if (serviceDefInterface.equals(validadorDelegateImpl_PortClass)) {
                return getValidadorDelegateImplPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(serviceDefInterface);
    }
    
    public com.msaf.validador.wsclient.ValidadorDelegateImpl getValidadorDelegateImplPort() {
        String[] roles = new String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_ValidadorDelegateImplPort_QNAME));
        handlerChain.setRoles(roles);
        com.msaf.validador.wsclient.ValidadorDelegateImpl_Stub stub = new com.msaf.validador.wsclient.ValidadorDelegateImpl_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
}
