// This class was generated by the JAXRPC RI, do not edit.
// Contents subject to change without notice.

package com.msaf.validador.wsclient;

import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.streaming.*;
import com.sun.xml.rpc.soap.message.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.lang.reflect.*;
import java.lang.Class;
import com.sun.xml.rpc.client.SenderException;
import com.sun.xml.rpc.client.*;
import com.sun.xml.rpc.client.http.*;
import javax.xml.rpc.handler.*;
import javax.xml.rpc.JAXRPCException;
import javax.xml.rpc.soap.SOAPFaultException;

public class ValidadorDelegateImpl_Stub
    extends com.sun.xml.rpc.client.StubBase
    implements com.msaf.validador.wsclient.ValidadorDelegateImpl {
    
    
    /*
     *  public constructor
     */
    public ValidadorDelegateImpl_Stub(HandlerChain handlerChain) {
        super(handlerChain);
        _setProperty(ENDPOINT_ADDRESS_PROPERTY, "http://200.189.181.70:8080/ValidadorDelegateImplService/ValidadorDelegateImpl");
    }
    
    /*
     *  implementation of consultaCliente
     */
    public javax.xml.soap.SOAPElement[] consultaCliente(java.lang.String arg0, int arg1, int arg2, java.lang.String arg3)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(consultaCliente_OPCODE);
            
            com.msaf.validador.wsclient.ConsultaCliente _myConsultaCliente = new com.msaf.validador.wsclient.ConsultaCliente();
            _myConsultaCliente.setArg0(arg0);
            _myConsultaCliente.setArg1(arg1);
            _myConsultaCliente.setArg2(arg2);
            _myConsultaCliente.setArg3(arg3);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_consultaCliente_consultaCliente_QNAME);
            _bodyBlock.setValue(_myConsultaCliente);
            _bodyBlock.setSerializer(myConsultaCliente_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "");
            
            _send((String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            com.msaf.validador.wsclient.ConsultaClienteResponse _result = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (com.msaf.validador.wsclient.ConsultaClienteResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (com.msaf.validador.wsclient.ConsultaClienteResponse)_responseObj;
            }
            
            return _result.get_return();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    
    /*
     *  this method deserializes the response structure in the body
     */
    protected void _readFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState  state) throws Exception {
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case consultaCliente_OPCODE:
                _deserialize_consultaCliente(bodyReader, deserializationContext, state);
                break;
            default:
                throw new SenderException("sender.response.unrecognizedOperation", Integer.toString(opcode));
        }
    }
    
    
    
    /*
     * This method deserializes the body of the consultaCliente operation.
     */
    private void _deserialize_consultaCliente(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        Object myConsultaClienteResponseObj =
            myConsultaClienteResponse_LiteralSerializer.deserialize(ns1_consultaCliente_consultaClienteResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_consultaCliente_consultaClienteResponse_QNAME);
        bodyBlock.setValue(myConsultaClienteResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    
    
    
    public String _getEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public void _setEncodingStyle(String encodingStyle) {
        throw new UnsupportedOperationException("cannot set encoding style");
    }
    
    
    
    
    
    /*
     * This method returns an array containing (prefix, nsURI) pairs.
     */
    protected String[] _getNamespaceDeclarations() {
        return myNamespace_declarations;
    }
    
    /*
     * This method returns an array containing the names of the headers we understand.
     */
    public QName[] _getUnderstoodHeaders() {
        return understoodHeaderNames;
    }
    
    public void _initialize(InternalTypeMappingRegistry registry) throws Exception {
        super._initialize(registry);
        myConsultaClienteResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.msaf.validador.wsclient.ConsultaClienteResponse.class, ns1_consultaClienteResponse_TYPE_QNAME);
        myConsultaCliente_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.msaf.validador.wsclient.ConsultaCliente.class, ns1_consultaCliente_TYPE_QNAME);
    }
    
    private static final QName _portName = new QName("http://webservices.validador.msaf.com/", "ValidadorDelegateImplPort");
    private static final int consultaCliente_OPCODE = 0;
    private static final QName ns1_consultaCliente_consultaCliente_QNAME = new QName("http://webservices.validador.msaf.com/", "consultaCliente");
    private static final QName ns1_consultaCliente_TYPE_QNAME = new QName("http://webservices.validador.msaf.com/", "consultaCliente");
    private CombinedSerializer myConsultaCliente_LiteralSerializer;
    private static final QName ns1_consultaCliente_consultaClienteResponse_QNAME = new QName("http://webservices.validador.msaf.com/", "consultaClienteResponse");
    private static final QName ns1_consultaClienteResponse_TYPE_QNAME = new QName("http://webservices.validador.msaf.com/", "consultaClienteResponse");
    private CombinedSerializer myConsultaClienteResponse_LiteralSerializer;
    private static final String[] myNamespace_declarations =
                                        new String[] {
                                            "ns0", "http://webservices.validador.msaf.com/"
                                        };
    
    private static final QName[] understoodHeaderNames = new QName[] {  };
}
