// This class was generated by the JAXRPC RI, do not edit.
// Contents subject to change without notice.

package com.msaf.validador.wsclient;

import javax.xml.rpc.*;

public interface ValidadorDelegateImplService extends javax.xml.rpc.Service {
    public com.msaf.validador.wsclient.ValidadorDelegateImpl getValidadorDelegateImplPort();
}
