// This class was generated by the JAXRPC RI, do not edit.
// Contents subject to change without notice.

package com.msaf.validador.wsclient;

public interface ValidadorDelegateImpl extends java.rmi.Remote {
    public javax.xml.soap.SOAPElement[] consultaCliente(java.lang.String arg0, int arg1, int arg2, java.lang.String arg3) throws 
         java.rmi.RemoteException;
}
